stages:
  - prepare
  - test
  - build
  - pack

.prepare: &prepare
  image: node:7.2
  script: 
    - npm install
  stage: prepare
  artifacts:
    paths:
      - "$PROJECT/node_modules/"
    expire_in: 1 week
    when: always

.test: &test
  image: node:7.2
  dependencies:
    - prepare:recipe-book
  script: 
    - npm run-script test
  stage: test

.build: &build
  image: node:7.2
  dependencies:
    - prepare:recipe-book
  script:
    - npm run-script build
    - npm run-script sass
  stage: build
  artifacts:
    paths: 
      - "$PROJECT/build/"
    expire_in: 1 week
    when: always

.pack: &pack
  image: node:7.2
  dependencies:
    - build:recipe-book
  script:
    - npm run-script pack
  stage: pack

prepare:recipe-book:
  <<: *prepare
  variables:
    PROJECT: .

test:
  <<: *test

build:recipe-book:
  <<: *build
  variables:
    PROJECT: .

pack:
  <<: *pack
