stages:
  - prepare
  - test
  - build
  - pack

.prepare: &prepare
  image: node:7.2
  script: 
    - npm install
  stage: prepare
  artifacts:
    paths:
      - "$PROJECT/node_modules/"
    expire_in: 1 week
    when: always

.test: &test
  image: registry.gitlab.com/bencraig/recipe-book:latest
  dependencies:
    - prepare:recipe-book
  script: 
    - grunt
  stage: test

.build: &build
  image: registry.gitlab.com/bencraig/recipe-book:latest
  dependencies:
    - prepare:recipe-book
  script:
    - npm run-script build
    - npm run-script sass
  stage: build
  artifacts:
    paths: 
      - "$PROJECT/build/"
    expire_in: 1 week
    when: always

.pack: &pack
  image: registry.gitlab.com/bencraig/recipe-book:latest
  dependencies:
    - build:recipe-book
  script:
    - npm run-script pack
  stage: pack

prepare:recipe-book:
  <<: *prepare

test:
  <<: *test

build:recipe-book:
  <<: *build

pack:
  <<: *pack
