stages:
  - prepare
  - test
  - build
  - pack

prepare:
  image: node:7.2
  script: 
    - npm install
  stage: build

test:
  # image: https://gitlab.com/bencraig/recipe-book.git
  dependencies:
    - prepare
  script: 
    - grunt
  stage: test


build:
  dependencies:
    - test
  script:
    - npm run-script build
    - npm run-script sass

pack:
  dependencies:
    - build
  script:
    - npm run-script pack
