stages:
  - prepare
  - test
  - build
  - pack

.prepare: &prepare
  image: node:7.2
  script: 
    - npm install
  stage: prepare

.test: &test
  # image: https://gitlab.com/bencraig/recipe-book.git
  # dependencies:
  #   - prepare
  script: 
    - grunt
  stage: test

.build: &build
  # dependencies:
  #   - test
  script:
    - npm run-script build
    - npm run-script sass
  stage: build

.pack: &pack
  # dependencies:
  #   - build
  script:
    - npm run-script pack
  stage: pack

prepare:
  <<: *prepare

test:
  <<: *test

build:
  <<: *build

pack:
  <<: *pack
