stages:
  - prepare
  - transpile
  - test
  - build
  - pack

.prepare: &prepare
  image: node:10.14
  script: 
    - npm install
  stage: prepare
  artifacts:
    paths:
      - "$PROJECT/node_modules/"
    expire_in: 1 week
    when: always

.transpile: &transpile
  image: node:10.14
  dependencies:
    - prepare:recipe-book
  stage: transpile
  script:
    - npm run build
  artifacts:
    paths: 
      - "$PROJECT/build/"
    expire_in: 1 week
    when: always

.test: &test
  image: node:10.14
  dependencies:
    - transpile
  script: 
    - npm run-script unit-tests
  stage: test

.build: &build
  image: node:10.14
  dependencies:
    - prepare:recipe-book
  script:
    - npm run-script sass
  stage: build
  artifacts:
    paths: 
      - "$PROJECT/public/css"
    expire_in: 1 week
    when: always

.pack: &pack
  image: node:10.14
  dependencies:
    - build:recipe-book
  script:
    - npm run-script pack
  stage: pack

prepare:recipe-book:
  <<: *prepare
  variables:
    PROJECT: .

transpile:
  <<: *transpile
  variables:
    PROJECT: .

test:
  <<: *test

build:recipe-book:
  <<: *build
  variables:
    PROJECT: .

pack:
  <<: *pack
