stages:
  - prepare
  - transpile
  - test
  - pack

.prepare: &prepare
  image: node:10.14
  script: 
    - npm install
  stage: prepare
  artifacts:
    paths:
      - "$PROJECT/node_modules/"
    expire_in: 1 week
    when: always

.transpile: &transpile
  image: node:10.14
  dependencies:
    - prepare:recipe-book
  stage: transpile
  script:
    - npm run build
  artifacts:
    paths: 
      - "$PROJECT/build/"
    expire_in: 1 week
    when: always

.test: &test
  image: registry.gitlab.com/alertlabs/devops/webapp-build:latest
  allow_failure: true
  script: 
    - npm run-script unit-tests
  stage: test

.pack: &pack
  image: node:10.14
  script:
    - pwd
    - npm run-script pack
  stage: pack

prepare:recipe-book:
  <<: *prepare
  variables:
    PROJECT: .

transpile:
  <<: *transpile
  variables:
    PROJECT: .

test:
  <<: *test

pack:
  <<: *pack
